// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission6.Models;

namespace mission6.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220209182025_NewResponses")]
    partial class NewResponses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission6.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.ToTable("NewResponses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Task = "IS Homework"
                        },
                        new
                        {
                            ApplicationId = 2,
                            Task = "Spending time with wife"
                        },
                        new
                        {
                            ApplicationId = 3,
                            Task = "Intern"
                        });
                });

            modelBuilder.Entity("mission6.Models.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
